{
    "generated_at": "2022-11-13T09:08:22Z",
    "vulnerabilities": [
        {
            "source": {
                "label": "~call_2 = ret_flask.request.view_args.get('command')",
                "line_number": 12,
                "path": "/app/exception_3_false_positive.py"
            },
            "source_trigger_word": "request.view_args.get(",
            "sink": {
                "label": "~call_3 = ret_eval(command)",
                "line_number": 18,
                "path": "/app/exception_3_false_positive.py"
            },
            "sink_trigger_word": "eval(",
            "type": "Vulnerability",
            "reassignment_nodes": [
                {
                    "label": "command = ~call_2",
                    "line_number": 12,
                    "path": "/app/exception_3_false_positive.py"
                }
            ]
        }
    ]
}